name: setup tauri environment
description: Set up the Tauri environment

inputs:
  tauri-app-path:
    description: Working directory for the Tauri project
    required: true
  tauri-frontend-path:
    description: Path to the webapp frontend
    required: true
  rust-version:
    description: Rust version to install
    required: true
  pnpm-version:
    description: PNPM version to install
    required: true

runs:
  using: composite
  steps:
    - name: Download webapp build artifacts
      uses: actions/download-artifact@v8.0.1
      with:
        name: webapp-bundle
        path: ${{ inputs.tauri-frontend-path }}/dist

    - name: Rust toolchain setup
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ inputs.rust-version }}

    - name: Cache cargo registry
      uses: actions/cache@v5.0.5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-registry-${{ inputs.rust-version }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ inputs.rust-version }}-

    - name: Cache cargo target
      uses: actions/cache@v5.0.5
      with:
        path: |
          ${{ inputs.tauri-app-path }}/target
        key: cargo-target-${{ runner.os }}-${{ inputs.rust-version }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-target-${{ runner.os }}-${{ inputs.rust-version }}-

    - name: Cache cargo bin
      uses: actions/cache@v5.0.5
      with:
        path: |
          ~/.cargo/bin/cargo-tauri
          ~/.cargo/bin/cargo-tauri.exe
        key: cargo-bin-${{ runner.os }}-${{ inputs.rust-version }}

    - name: Install linux dependencies
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends --no-install-suggests -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev xdg-utils

    - name: Prepare repository
      working-directory: ${{ inputs.tauri-app-path }}
      shell: bash
      run: |
        jq '.build.beforeBuildCommand = ""' tauri.conf.json > tmp.json && mv tmp.json tauri.conf.json
        corepack enable && corepack prepare pnpm@${{ inputs.pnpm-version }} --activate && corepack enable pnpm
        command -v cargo-tauri || cargo install --locked tauri-cli

    - name: Install Webapp production dependencies
      working-directory: ${{ inputs.tauri-frontend-path }}
      shell: bash
      run: pnpm install --frozen-lockfile --prod

    - name: Clean stale artifacts
      working-directory: ${{ inputs.tauri-app-path }}
      shell: bash
      run: |
        rm -rf "./target/release/assets"
        rm -rf "./target/release/bundle"
        rm -rf "./target/release/examples"
        rm -rf "./target/release/icons"
        rm -rf "./target/release/plugins"
        rm -rf "./target/release/widgets"
        rm -rf "./target/release/LICENSE"
