name: "Setup Rust"
description: "Setup Rust environment for GitHub Actions"
inputs:
  rust-version:
    description: "Version Spec of the version to use. Examples: stable, nightly, 1.86.0."
    default: "stable"
  cache-dependency-path:
    description: "Used to specify the path to a dependency file (Cargo.lock)."
    default: "**/Cargo.lock"
runs:
  using: "composite"
  steps:
    - name: Install Rust
      shell: bash
      run: |
        if [ -x "$(command -v rustup)" ]; then
          rustup self uninstall -y
        fi
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain ${{ inputs.rust-version }}
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Check Rust version
      shell: bash
      run: rustc --version

    - name: Cache rust store
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ inputs.rust-version }}-${{ hashFiles(inputs.cache-dependency-path) }}
        restore-keys: |
          ${{ runner.os }}-cargo-
