[package]
name = "unichat"
version = "1.5.0-beta.2"
description = "A cross-platform chat integration without API keys, OAuth, or accounts."
authors = ["Voguh <voguhofc@protonmail.com>"]
homepage = "https://codeberg.org/unichat/unichat"
license = "EPL-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
anyhow = { version = "=1.0.104", features = ["backtrace"] }
axum = { version = "=0.8.9", features = ["ws"] }
base64 = "=0.23.1"
futures = "=0.3.34"
if-addrs = "=0.15.0"
indexmap = { version = "=2.14.0", features = ["serde"] }
infer = "=0.22.0"
log = "=0.4.33"
mime_guess = "=2.0.5"
mlua = { version = "=0.12.0", features = ["lua54", "vendored", "serde", "send"] }
moka = { version = "=0.12.16", features = ["sync"] }
rand = "=0.10.2"
regex = "=1.13.1"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = { version = "=1.0.151", features = ["preserve_order"] }
serde_plain = "=1.0.2"
serde-saphyr = "=1.0.1"
tauri = { version = "=2.11.5", features = ["native-tls"] }
tauri-plugin-dialog = "=2.7.2"
tauri-plugin-log = "=2.9.0"
tauri-plugin-opener = "=2.5.4"
tauri-plugin-store = "=2.4.4"
tokio = { version = "=1.53.1", features = ["full"] }
ureq = { version = "=3.4.0", default-features = false, features = ["json", "native-tls"] }
url = { version = "=2.5.8", features = ["serde"] }
