name: main.yaml

on:
  push:
    branches:
      - '**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

env:
  NODE_VERSION: '24.16.0'
  PNPM_VERSION: '10.33.4'
  RUST_VERSION: '1.95.0'
  YQ_VERSION: 'v4.53.2'

jobs:
  check_license_headers:
    runs-on: ubuntu-24.04
    env:
      TAURI_APP_PATH: ${{ forgejo.workspace }}
      TAURI_FRONTEND_PATH: ${{ forgejo.workspace }}/webapp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Check license headers
        run: |
          LOG_LEVEL=debug ./zztools/check-license-header.py

  bundle-webapp:
    runs-on: ubuntu-24.04
    if: forgejo.event_name == 'workflow_dispatch' || forgejo.ref == 'refs/heads/main' || startsWith(forgejo.ref, 'refs/heads/stable/') || startsWith(forgejo.ref, 'refs/tags/')
    needs: [check_license_headers]
    env:
      TAURI_APP_PATH: ${{ forgejo.workspace }}
      TAURI_FRONTEND_PATH: ${{ forgejo.workspace }}/webapp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: ${{ env.TAURI_FRONTEND_PATH }}/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ${{ env.TAURI_FRONTEND_PATH }}
        run: |
          pnpm install --frozen-lockfile

      - name: Build webapp
        working-directory: ${{ env.TAURI_FRONTEND_PATH }}
        run: |
          pnpm build:ui

      - name: Upload webapp build artifacts
        uses: forgejo/upload-artifact@v5
        with:
          name: webapp-build
          path: ${{ env.TAURI_FRONTEND_PATH }}/dist

  package:
    runs-on: ubuntu-24.04
    needs: [bundle-webapp]
    strategy:
      matrix:
        include:
          - target: linux
            rust_target: x86_64-unknown-linux-gnu
            release_path: target/release
            bundle_path: target/release/bundle
            build_command: cargo tauri build
          - target: windows
            rust_target: x86_64-pc-windows-msvc
            release_path: target/x86_64-pc-windows-msvc/release
            bundle_path: target/x86_64-pc-windows-msvc/release/bundle
            build_command: cargo tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
    env:
      TAURI_APP_PATH: ${{ forgejo.workspace }}
      TAURI_FRONTEND_PATH: ${{ forgejo.workspace }}/webapp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Download webapp build artifacts
        uses: forgejo/download-artifact@v7
        with:
          name: webapp-build
          path: ${{ env.TAURI_FRONTEND_PATH }}/dist

      - name: Rust toolchain setup
        uses: ./.forgejo/actions/rust-toolchain
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.rust_target }}

      - name: Cache cargo registry
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-registry-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ env.RUST_VERSION }}-

      - name: Cache cargo target
        uses: actions/cache@v5.0.5
        with:
          path: |
            target
          key: cargo-target-${{ matrix.target }}-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-target-${{ matrix.target }}-${{ env.RUST_VERSION }}-

      - name: Cache cargo bin
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.cargo/bin/cargo-xwin
            ~/.cargo/bin/cargo-tauri
          key: cargo-bin-${{ matrix.target }}-${{ env.RUST_VERSION }}

      - name: Prepare build environment
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --no-install-suggests -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev xdg-utils
          jq '.build.beforeBuildCommand = ""' tauri.conf.json > tmp.json && mv tmp.json tauri.conf.json
          corepack enable && corepack prepare pnpm@${{ env.PNPM_VERSION}} --activate && corepack enable pnpm
          command -v cargo-tauri || cargo install --locked tauri-cli
          if [[ "${{ matrix.target }}" == "windows" ]]; then
              sudo apt-get install --no-install-recommends --no-install-suggests -y nsis clang lld llvm
              command -v cargo-xwin || cargo install --locked cargo-xwin
          fi

      - name: Install Webapp production dependencies
        working-directory: ${{ env.TAURI_FRONTEND_PATH }}
        run: |
          pnpm install --frozen-lockfile --prod

      - name: Clean stale artifacts
        run: |
          rm -rf ${{ matrix.release_path }}/assets
          rm -rf ${{ matrix.release_path }}/bundle
          rm -rf ${{ matrix.release_path }}/examples
          rm -rf ${{ matrix.release_path }}/icons
          rm -rf ${{ matrix.release_path }}/plugins
          rm -rf ${{ matrix.release_path }}/widgets
          rm -rf ${{ matrix.release_path }}/LICENSE

      - name: Run build app
        run: ${{ matrix.build_command }}

      - name: Upload build artifacts
        uses: forgejo/upload-artifact@v5
        with:
          name: ${{ matrix.target }}-bundles
          path: ${{ forgejo.workspace }}/${{ matrix.bundle_path }}

  publish:
    if: startsWith(forgejo.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    needs: [package]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Download windows build artifacts
        uses: forgejo/download-artifact@v7
        with:
          name: windows-bundles
          path: ${{ forgejo.workspace }}/target/windows

      - name: Download linux build artifacts
        uses: forgejo/download-artifact@v7
        with:
          name: linux-bundles
          path: ${{ forgejo.workspace }}/target/linux

      - name: Install yq
        run: |
          case "$(uname -m)" in
            x86_64|amd64)  ARCH="amd64" ;;
            aarch64|arm64) ARCH="arm64" ;;
            *) echo "Unsupported architecture." && exit 1 ;;
          esac
          mkdir -p "$HOME/.local/bin"
          wget "https://github.com/mikefarah/yq/releases/download/${{ env.YQ_VERSION }}/yq_linux_${ARCH}" -O "$HOME/.local/bin/yq"
          chmod +x "$HOME/.local/bin/yq"
          echo "$HOME/.local/bin" >> "$FORGEJO_PATH"

      - name: Check version consistency
        run: |
          export CARGO_PACKAGE_VERSION="$(yq -oy '.package.version' Cargo.toml)"
          TAG_NAME="${FORGEJO_REF#refs/tags/}"
          if [ "$CARGO_PACKAGE_VERSION" != "$TAG_NAME" ]; then
            echo "Error: The version in Cargo.toml ($CARGO_PACKAGE_VERSION) does not match the release tag ($TAG_NAME)."
            exit 1
          fi

      - name: Move build artifacts
        run: |
          export VERSION="${FORGEJO_REF#refs/tags/}"
          mkdir -p ${{ forgejo.workspace }}/dist
          cp ${{ forgejo.workspace }}/target/linux/appimage/*.AppImage ${{ forgejo.workspace }}/dist/unichat-$VERSION.AppImage
          cp ${{ forgejo.workspace }}/target/linux/deb/*.deb ${{ forgejo.workspace }}/dist/unichat-$VERSION.deb
          cp ${{ forgejo.workspace }}/target/linux/rpm/*.rpm ${{ forgejo.workspace }}/dist/unichat-$VERSION.rpm
          cp ${{ forgejo.workspace }}/target/windows/nsis/*.exe ${{ forgejo.workspace }}/dist/unichat-$VERSION-setup.exe
          for file in ${{ forgejo.workspace }}/dist/*; do
            if [ -f "$file" ]; then
              (cd "$(dirname "$file")" && sha256sum "$(basename "$file")" > "$(basename "$file").sha256")
            fi
          done

      - name: Create and upload to Forgejo Release
        uses: actions/forgejo-release@v2.11.3
        with:
          direction: upload
          prerelease: true
          release-dir: ${{ forgejo.workspace }}/dist
