name: main.yaml

on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

env:
  NODE_VERSION: '24.10.0'
  PNPM_VERSION: '10.30.3'
  RUST_VERSION: '1.92.0'

jobs:
  bundle-webapp:
    runs-on: ubuntu-24.04
    env:
      TAURI_APP_PATH: ${{ forgejo.workspace }}
      TAURI_FRONTEND_PATH: ${{ forgejo.workspace }}/webapp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: ${{ env.TAURI_FRONTEND_PATH }}/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ${{ env.TAURI_FRONTEND_PATH }}
        run: |
          pnpm install --frozen-lockfile

      - name: Build webapp
        working-directory: ${{ env.TAURI_FRONTEND_PATH }}
        run: |
          pnpm build:ui

      - name: Upload webapp build artifacts
        uses: forgejo/upload-artifact@v5
        with:
          name: webapp-build
          path: ${{ env.TAURI_FRONTEND_PATH }}/dist

  package:
    runs-on: ubuntu-24.04
    needs: [bundle-webapp]
    strategy:
      matrix:
        include:
          - target: linux
            rust_target: x86_64-unknown-linux-gnu
            bundle_path: target/release/bundle
            build_command: cargo tauri build
          - target: windows
            rust_target: x86_64-pc-windows-msvc
            bundle_path: target/x86_64-pc-windows-msvc/release/bundle
            build_command: cargo tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
    env:
      TAURI_APP_PATH: ${{ forgejo.workspace }}
      TAURI_FRONTEND_PATH: ${{ forgejo.workspace }}/webapp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Download webapp build artifacts
        uses: forgejo/download-artifact@v7
        with:
          name: webapp-build
          path: ${{ env.TAURI_FRONTEND_PATH }}/dist

      - name: Rust toolchain setup
        uses: ./.forgejo/actions/rust-toolchain
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.rust_target }}

      - name: Cache cargo registry
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo target
        uses: actions/cache@v5.0.5
        with:
          path: |
            target
          key: cargo-target-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-target-${{ matrix.target }}-

      - name: Cache cargo bin
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.cargo/bin/cargo-xwin
            ~/.cargo/bin/cargo-tauri
          key: cargo-bin-${{ matrix.target }}-${{ env.RUST_VERSION }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Prepare build environment
        run: |
          sudo apt update
          sudo apt install --no-install-recommends --no-install-suggests -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev xdg-utils
          jq '.build.beforeBuildCommand = ""' tauri.conf.json > tmp.json && mv tmp.json tauri.conf.json
          corepack enable && corepack prepare pnpm@${{ env.PNPM_VERSION}} --activate && corepack enable pnpm
          command -v cargo-tauri || cargo install --locked tauri-cli
          if [[ "${{ matrix.target }}" == "windows" ]]; then
              sudo apt install --no-install-recommends --no-install-suggests -y nsis clang lld llvm
              command -v cargo-xwin || cargo install --locked cargo-xwin
          fi

      - name: Run build app
        run: ${{ matrix.build_command }}

      - name: Upload build artifacts
        uses: forgejo/upload-artifact@v5
        with:
          name: ${{ matrix.target }}-bundles
          path: ${{ forgejo.workspace }}/${{ matrix.bundle_path }}

  publish:
    if: startsWith(forgejo.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    needs: [package]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Download windows build artifacts
        uses: forgejo/download-artifact@v7
        with:
          name: windows-bundles
          path: ${{ forgejo.workspace }}/target/windows

      - name: Download linux build artifacts
        uses: forgejo/download-artifact@v7
        with:
          name: linux-bundles
          path: ${{ forgejo.workspace }}/target/linux

      - name: Setup version
        id: setup_version
        run: |
          export CARGO_PACKAGE_VERSION="$(cargo pkgid | cut -d# -f2)"
          if [[ "$FORGEJO_REF" == refs/tags/* ]]; then
            TAG_NAME="${FORGEJO_REF#refs/tags/}"
            if [ "$CARGO_PACKAGE_VERSION" != "$TAG_NAME" ]; then
              echo "Error: The version in Cargo.toml ($CARGO_PACKAGE_VERSION) does not match the release tag ($TAG_NAME)."
              exit 1
            fi
            echo "revision=$TAG_NAME" >> $FORGEJO_OUTPUT
          else
            export SHORT_CARGO_VERSION="$(echo $CARGO_PACKAGE_VERSION | cut -d '-' -f1)"
            export NEW_VERSION="$SHORT_CARGO_VERSION+$FORGEJO_SHA"
            sed -i "s/^version = \"$CARGO_PACKAGE_VERSION\"/version = \"$NEW_VERSION\"/" "Cargo.toml"
            echo "revision=$NEW_VERSION" >> $FORGEJO_OUTPUT
          fi

      - name: Print revision
        run: echo "Revision is ${{ steps.setup_version.outputs.revision }}"

      - name: Move build artifacts
        run: |
          export VERSION="${{ steps.setup_version.outputs.revision }}"
          mkdir -p ${{ forgejo.workspace }}/dist
          cp ${{ forgejo.workspace }}/target/linux/appimage/*.AppImage ${{ forgejo.workspace }}/dist/unichat-$VERSION.AppImage
          cp ${{ forgejo.workspace }}/target/linux/deb/*.deb ${{ forgejo.workspace }}/dist/unichat-$VERSION.deb
          cp ${{ forgejo.workspace }}/target/linux/rpm/*.rpm ${{ forgejo.workspace }}/dist/unichat-$VERSION.rpm
          cp ${{ forgejo.workspace }}/target/windows/nsis/*.exe ${{ forgejo.workspace }}/dist/unichat-$VERSION-setup.exe
          for file in ${{ forgejo.workspace }}/dist/*; do
            if [ -f "$file" ]; then
              sha256sum "$file" > "${file}.sha256"
            fi
          done

      - name: Create and upload to Forgejo Release
        uses: actions/forgejo-release@v2.11.3
        with:
          direction: upload
          prerelease: true
          release-dir: ${{ forgejo.workspace }}/dist
