name: "Setup Tauri"
description: "Setup Tauri environment for GitHub Actions"
inputs:
  github-workspace:
    description: "Path to the GitHub workspace. Defaults to the root of the repository."
    default: "${{ github.workspace }}"
  rust-version:
    description: "Rust version to use. Examples: stable, nightly, 1.86.0."
    default: "stable"
  node-version:
    description: "Node.JS version to use. Examples: 22.x, 20.15.1, >=20.15.0."
    default: "22.14.0"
  pnpm-version:
    description: "PNPM version to use. Examples: 10.x, 10.7.1, >=10.7.0."
    default: "10.7.1"
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: ./.github/actions/setup-rust
      with:
        rust-version: ${{ inputs.rust-version }}

    - name: Setup Node.JS
      uses: ./.github/actions/setup-node
      with:
        node-version: ${{ inputs.node-version }}
        pnpm-version: ${{ inputs.pnpm-version }}

    - name: Setup Tauri
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
        if [[ -z "$(command -v tq 2>/dev/null)"  ]]; then
          echo "Installing tq..."
          cargo install tomlq --locked
        fi
        cargo install tauri-cli --locked --version "$(tq -r -f "${{ inputs.github-workspace }}/Cargo.toml" '.dependencies.tauri.version')"
