#!/usr/bin/env node
import { register } from "node:module";
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
globalThis.__filename = __filename;
globalThis.__dirname = __dirname;

register(pathToFileURL(path.resolve(__dirname, "scripts", "utils", "_hook.js")));
import(path.resolve(__dirname, `scripts/${path.basename(__filename)}.js`))
