#!/bin/bash
set -euo pipefail

source "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/utils/main.sh";

new_version="${1:-}";
if ! semver_verify "$new_version"; then
    logger_error "Invalid version format. Please provide a valid semantic version (e.g., 1.0.0).";
    exit 1;
fi

if ! confirm "Are you sure you want to release version '$new_version'?"; then
    logger_info "Release cancelled.";
    exit 0;
fi

cargo_toml_path="$ROOT_PATH/Cargo.toml";
current_version="$(cat "$cargo_toml_path" | grep '^version =' | head -n1 | cut -d '"' -f2)";

logger_info "Checking '\033[33mCargo.toml\033[0m' current version...";
cmp="$(semver_compare "$new_version" "$current_version")";
if [[ "$cmp" != "1" ]]; then
    logger_error "New version '$new_version' must be greater than the current version '$current_version'.";
    exit 1;
fi

logger_info "Updating version from '$current_version' to '$new_version'.";
sed -i.bak "s/^version = \".*\"/version = \"$new_version\"/" "$cargo_toml_path";
rm "${cargo_toml_path}.bak";

logger_info "Updating '\033[33mREADME.md\033[0m' version references.";
readme_path="$ROOT_PATH/README.md";
readme_current_version="$(echo "$current_version" | sed 's/-/--/g')";
readme_new_version="$(echo "$new_version" | sed 's/-/--/g')";
sed -i.bak "s/version-v$readme_current_version/version-v$readme_new_version/g" "$readme_path";
rm "${readme_path}.bak";

logger_info "Running tests and building project...";
pnpm install --frozen-lockfile;
pnpm test run --passWithNoTests;
pnpm build:ui;
cargo test --all-targets --all-features;
cargo tauri build;

logger_info "Committing changes...";
git add "$cargo_toml_path" "$readme_path" "$ROOT_PATH/Cargo.lock";
git commit -m "chore: release version $new_version";
git tag -a "${new_version}" -m "$new_version";
git push origin main --tags;
