name: release.yaml

on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

env:
  NODE_VERSION: '24.10.0'
  PNPM_VERSION: '10.7.1'
  RUST_VERSION: '1.92.0'
  TAURI_APP_PATH: ${{ github.workspace }}
  TAURI_FRONTEND_PATH: ${{ github.workspace }}/webapp

jobs:
  webapp-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: ${{ env.TAURI_FRONTEND_PATH }}/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ${{ env.TAURI_FRONTEND_PATH }}
        run: |
          pnpm install --frozen-lockfile

      - name: Build webapp
        working-directory: ${{ env.TAURI_FRONTEND_PATH }}
        run: |
          pnpm build:ui

      - name: Upload webapp artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: webapp-dist
          path: ${{ env.TAURI_FRONTEND_PATH }}/dist

  package-linux:
    runs-on: ubuntu-24.04
    needs: [webapp-build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Download webapp artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: webapp-dist
          path: ${{ env.TAURI_FRONTEND_PATH }}/dist

      - name: Prepare build environment
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
          npm install -g @tauri-apps/cli
          node -e "let fs = require('fs'); let path = require('path'); let cPath = path.join(__dirname, 'tauri.conf.json'); let c = JSON.parse(fs.readFileSync(cPath)); c.build.beforeBuildCommand = ''; fs.writeFileSync(cPath, JSON.stringify(c, null, 4));"

      - name: Rust toolchain setup
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Run build app
        run: |
          tauri build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: linux-bundles
          path: ${{ github.workspace }}/target/release/bundle

  package-windows:
    runs-on: ubuntu-24.04
    needs: [webapp-build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Download webapp artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: webapp-dist
          path: ${{ env.TAURI_FRONTEND_PATH }}/dist

      - name: Prepare build environment
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
          sudo apt install --no-install-recommends -y nsis clang lld llvm
          npm install -g @tauri-apps/cli
          node -e "let fs = require('fs'); let path = require('path'); let cPath = path.join(__dirname, 'tauri.conf.json'); let c = JSON.parse(fs.readFileSync(cPath)); c.build.beforeBuildCommand = ''; fs.writeFileSync(cPath, JSON.stringify(c, null, 4));"

      - name: Rust toolchain setup
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-pc-windows-msvc

      - name: Run build app
        run: |
          cargo install cargo-xwin
          tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-bundles
          path: ${{ github.workspace }}/target/x86_64-pc-windows-msvc/release/bundle

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    needs: [package-linux, package-windows]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Download windows build artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          name: windows-bundles
          path: ${{ github.workspace }}/target/windows

      - name: Download linux build artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          name: linux-bundles
          path: ${{ github.workspace }}/target/linux

      - name: Setup version
        id: setup_version
        run: |
          export CARGO_PACKAGE_VERSION="$(cargo pkgid | cut -d# -f2)"
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            if [ "$CARGO_PACKAGE_VERSION" != "$TAG_NAME" ]; then
              echo "Error: The version in Cargo.toml ($CARGO_PACKAGE_VERSION) does not match the release tag ($TAG_NAME)."
              exit 1
            fi
            echo "revision=$TAG_NAME" >> $GITHUB_OUTPUT
          else
            export SHORT_CARGO_VERSION="$(echo $CARGO_PACKAGE_VERSION | cut -d '-' -f1)"
            export NEW_VERSION="$SHORT_CARGO_VERSION+$GITHUB_SHA"
            sed -i "s/^version = \"$CARGO_PACKAGE_VERSION\"/version = \"$NEW_VERSION\"/" "Cargo.toml"
            echo "revision=$NEW_VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Print revision
        run: echo "Revision is ${{ steps.setup_version.outputs.revision }}"

      - name: Move build artifacts
        run: |
          export VERSION="${{ steps.setup_version.outputs.revision }}"
          mkdir -p ${{ github.workspace }}/dist
          cp ${{ github.workspace }}/target/linux/appimage/*.AppImage ${{ github.workspace }}/dist/unichat-$VERSION.AppImage
          cp ${{ github.workspace }}/target/linux/deb/*.deb ${{ github.workspace }}/dist/unichat-$VERSION.deb
          cp ${{ github.workspace }}/target/linux/rpm/*.rpm ${{ github.workspace }}/dist/unichat-$VERSION.rpm
          cp ${{ github.workspace }}/target/windows/nsis/*.exe ${{ github.workspace }}/dist/unichat-$VERSION-setup.exe
          for file in ${{ github.workspace }}/dist/*; do
            if [ -f "$file" ]; then
              sha256sum "$file" > "${file}.sha256"
            fi
          done

      - name: Create and upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          if [ -n "$(command -v gh)" ]; then
            echo "Creating GitHub Release for tag $TAG_NAME"
            echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
            gh release create "$TAG_NAME" --prerelease
            for file in ${{ github.workspace }}/dist/*; do
              if [ -f "$file" ]; then
                echo "Uploading $file to GitHub Release $TAG_NAME"
                gh release upload "$TAG_NAME" "$file"
              fi
            done
            echo "All files uploaded to GitHub Release successfully."
          else
            echo "GitHub CLI is not installed. Skipping upload to GitHub Release."
            exit 0
          fi
